<a href="?page=signup">Don't have an account? Sign up instead!:D</a>
<form action="index.php" method="POST">

    <label for="username">Username:</label>
    <input type="text" id="username" name="username">

    <label for="password">Password:</label>
    <input type="password" id="password" name="password" ">

    <input type="submit" class="button" name="login" value="login" onclick="hash()">
    
</form>